version: "3"

services:
  idref-api-derivationBnf:
    image: abesesr/idref:microservices-derivation-bnf
    container_name: idref-api-derivationBnf
    restart: unless-stopped
    environment:
      - URL_BNF=${URL_BNF}
      - URL_SOLR=${URL_SOLR}
      - URL_SRU=${URL_SRU}
      - PATTERN_ARK=${PATTERN_ARK}
      - PATTERN_RECORDID=${PATTERN_RECORDID}
      - URL_CHE=${URL_CHE}
      - URL_ORACLE=${URL_ORACLE}
    ports:
      - ${DERIVATION_BNF_HTTP_PORT:-6085}:8080
    labels:
      # pour envoyer les logs dans le puits de log de l'abes
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/processors.add_fields.fields.abes_appli=idref-api-derivationBnf"

  idref-api-derivationViaf:
    image: abesesr/idref:microservices-derivation-viaf
    container_name: idref-api-derivationViaf
    restart: unless-stopped
    environment:
      - URL_BNF=${URL_BNF}
      - URL_SOLR=${URL_SOLR}
      - URL_SRU=${URL_SRU}
      - PATTERN_ARK=${PATTERN_ARK}
      - PATTERN_RECORDID=${PATTERN_RECORDID}
      - URL_CHE=${URL_CHE}
      - URL_ORACLE=${URL_ORACLE}
    ports:
      - ${DERIVATION_VIAF_HTTP_PORT:-6085}:8080
    labels:
      # pour envoyer les logs dans le puits de log de l'abes
      - "co.elastic.logs/enabled=true"
      - "co.elastic.logs/processors.add_fields.target="
      - "co.elastic.logs/processors.add_fields.fields.abes_appli=idref-api-derivationViaf"